Repository 9oormthon-univ/2024_DANPOON_TEAM_42_FE, pull requests merged in 2024-11, with the labels that each got.

#7 [FEAT] 카카오맵 API 연결 및 내 주변 메인 UI 구현
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SWIPO-iOS/App/SWIPO_iOSApp.swift
  SWIPO-iOS/Assets.xcassets/Nearby/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/filter.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/filter.imageset/filter@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/filter.imageset/filter@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/location.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/location.imageset/location@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/location.imageset/location@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/search.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/search.imageset/search@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/search.imageset/search@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/tooltip.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/tooltip.imageset/tooltip@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/tooltip.imageset/tooltip@3x.png
  SWIPO-iOS/Extension/Custom/CustomTextField.swift
  SWIPO-iOS/Info.plist
  SWIPO-iOS/Main/MainView.swift
  SWIPO-iOS/Main/Nearby/MapView.swift
  SWIPO-iOS/Main/Nearby/MapViewController.swift
  SWIPO-iOS/Main/Nearby/NearbyView.swift
Labels: 👾 Feat

#9 [FEAT] Kakao, Apple Login 구현 및 키 관리
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/App/SWIPO_iOSApp.swift
  SWIPO-iOS/Assets.xcassets/Login/Contents.json
  SWIPO-iOS/Assets.xcassets/Login/apple_logo.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Login/apple_logo.imageset/apple_logo.png
  SWIPO-iOS/Assets.xcassets/Login/kakao_logo.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Login/kakao_logo.imageset/kakao_logo.png
  SWIPO-iOS/Assets.xcassets/Login/login_cloud.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Login/login_cloud.imageset/login_cloud.png
  SWIPO-iOS/Assets.xcassets/Login/login_logo.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Login/login_logo.imageset/login_logo.png
  SWIPO-iOS/Common/Util/AuthManager.swift
  SWIPO-iOS/Common/Util/secret.swift
  SWIPO-iOS/Info.plist
  SWIPO-iOS/Login/LoginView.swift
Labels: 👾 Feat

#12 [FEAT] Kakao, Apple Social Login 구현
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/App/SWIPO_iOSApp.swift
  SWIPO-iOS/Assets.xcassets/Login/Contents.json
  SWIPO-iOS/Assets.xcassets/Login/apple_logo.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Login/apple_logo.imageset/apple_logo.png
  SWIPO-iOS/Assets.xcassets/Login/kakao_logo.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Login/kakao_logo.imageset/kakao_logo.png
  SWIPO-iOS/Assets.xcassets/Login/login_cloud.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Login/login_cloud.imageset/login_cloud.png
  SWIPO-iOS/Assets.xcassets/Login/login_logo.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Login/login_logo.imageset/login_logo.png
  SWIPO-iOS/Common/AuthManager.swift
  SWIPO-iOS/Common/MainNavigationBar.swift
  SWIPO-iOS/Common/Secrets.swift
  SWIPO-iOS/Info.plist
  SWIPO-iOS/Login/LoginView.swift
Labels: 👾 Feat

#14 [FEAT] 내 주변 가맹점 UI 구현
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/Assets.xcassets/Extension/Contents.json
  SWIPO-iOS/Assets.xcassets/Extension/back_blank.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Extension/back_blank.imageset/back_blank.png
  SWIPO-iOS/Assets.xcassets/Extension/back_btn.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Extension/back_btn.imageset/back_btn.png
  SWIPO-iOS/Assets.xcassets/Extension/term_all_btn.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Extension/term_all_btn.imageset/term_all_btn.png
  SWIPO-iOS/Assets.xcassets/Extension/term_all_btn_color.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Extension/term_all_btn_color.imageset/term_all_btn_color.png
  SWIPO-iOS/Assets.xcassets/Extension/term_chk_btn.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Extension/term_chk_btn.imageset/term_chk_btn.png
  SWIPO-iOS/Assets.xcassets/Extension/term_chk_btn_color.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Extension/term_chk_btn_color.imageset/term_chk_btn_color.png
  SWIPO-iOS/Assets.xcassets/Extension/term_see_btn.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Extension/term_see_btn.imageset/term_see_btn.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/Store/down.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/Store/down.imageset/chevron-down@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/down.imageset/chevron-down@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/favorite.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/Store/favorite.imageset/favorite@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/favorite.imageset/favorite@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/heart.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/Store/heart.imageset/heart@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/heart.imageset/heart@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/heart_filled.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/Store/heart_filled.imageset/heart_filled@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/heart_filled.imageset/heart_filled@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/sample1.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/Store/sample1.imageset/sample1@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/sample1.imageset/sample1@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/sample2.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/Store/sample2.imageset/sample2@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/sample2.imageset/sample2@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/sample3.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/Store/sample3.imageset/image@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/sample3.imageset/image@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/up.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/Store/up.imageset/arrow-up@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/up.imageset/arrow-up@3x.png
  SWIPO-iOS/Common/NavigationBar.swift
  SWIPO-iOS/Main/Nearby/NearbyView.swift
  SWIPO-iOS/Main/Nearby/StoreList/StoreListView.swift
  SWIPO-iOS/Main/Nearby/StoreList/StoreModel.swift
  SWIPO-iOS/Main/Nearby/StoreList/StoreOptionView.swift
Labels: 👾 Feat

#16 [FEAT] 약관동의 UI 및 WebView 구현
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/Common/WebView.swift
  SWIPO-iOS/Join/Terms/TermsView.swift
  SWIPO-iOS/Login/LoginView.swift
Labels: 👾 Feat

#18 [FEAT] SwipointView UI 및 SwistoneGuide UI 구현
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/App/SWIPO_iOSApp.swift
  SWIPO-iOS/Assets.xcassets/Navigation/Contents.json
  SWIPO-iOS/Assets.xcassets/Navigation/question_circle_mark.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Navigation/question_circle_mark.imageset/swipoint_question_mark.png
  SWIPO-iOS/Assets.xcassets/Region/gyeonggi.imageset/ gyeonggi.png
  SWIPO-iOS/Assets.xcassets/Region/gyeonggi.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Region/sejong.imageset/ sejong.png
  SWIPO-iOS/Assets.xcassets/Region/sejong.imageset/Contents.json
  SWIPO-iOS/Common/GeoServiceManager.swift
  SWIPO-iOS/Login/LoginView.swift
  SWIPO-iOS/Main/Swipay/SwipayModel.swift
  SWIPO-iOS/Main/Swipay/SwipayView.swift
  SWIPO-iOS/Main/Swipay/SwipayViewModel.swift
  SWIPO-iOS/Main/Swipoint/LocationCertificationModel.swift
  SWIPO-iOS/Main/Swipoint/SwipointModel.swift
  SWIPO-iOS/Main/Swipoint/SwipointView.swift
  SWIPO-iOS/Main/Swipoint/SwipointViewModel.swift
  SWIPO-iOS/Main/Swipstone/SwipstoneGuideView.swift
Labels: 👾 Feat

#20 [FEAT] Swipoint Modal 구현
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/Assets.xcassets/Swipoint/Contents.json
  SWIPO-iOS/Assets.xcassets/Swipoint/swipoint_location.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Swipoint/swipoint_location.imageset/swipoint_location.png
  SWIPO-iOS/Main/Swipoint/LocationCertificationModal.swift
  SWIPO-iOS/Main/Swipoint/LocationCertificationModel.swift
  SWIPO-iOS/Main/Swipoint/LocationExistView.swift
  SWIPO-iOS/Main/Swipoint/LocationNewModal.swift
  SWIPO-iOS/Main/Swipoint/SwipointView.swift
  SWIPO-iOS/Main/Swipoint/SwipointViewModel.swift
Labels: 👾 Feat

#21 [FEAT] 페이 충전 UI 구현
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_add.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_add.imageset/add@2x.png
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_add.imageset/add@3x.png
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_character1.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_character1.imageset/swipay_character1@2x.png
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_character1.imageset/swipay_character1@3x.png
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_character2.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_character2.imageset/swipay_character2@2x.png
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_character2.imageset/swipay_character2@3x.png
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_character3.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_character3.imageset/swipay_character3@2x.png
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_character3.imageset/swipay_character3@3x.png
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_character4.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_character4.imageset/swipay_character4@2x.png
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_character4.imageset/swipay_character4@3x.png
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_refresh.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_refresh.imageset/refresh@2x.png
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_refresh.imageset/refresh@3x.png
  SWIPO-iOS/Main/Swipay/PayCharge/PayChargeView.swift
  SWIPO-iOS/Main/Swipay/SwipayView.swift
Labels: 👾 Feat

#37 [FEAT] Payment 구현
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/Main/Swipay/SwipayView.swift
  SWIPO-iOS/Payment/PaymentFinishView.swift
  SWIPO-iOS/Payment/PaymentView.swift
  SWIPO-iOS/Payment/QRScannerView.swift
Labels: 👾 Feat

#39 [REFACTOR] 툴팁 구현 및 수정
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/Assets.xcassets/Login/login_background.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Login/login_background.imageset/login_background.png
  SWIPO-iOS/Assets.xcassets/Payment/Contents.json
  SWIPO-iOS/Assets.xcassets/Payment/payment_camera.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Payment/payment_camera.imageset/payment_camera.png
  SWIPO-iOS/Assets.xcassets/Payment/payment_card_ex1.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Payment/payment_card_ex1.imageset/payment_card_ex1.png
  SWIPO-iOS/Assets.xcassets/Payment/payment_cloud.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Payment/payment_cloud.imageset/payment_cloud.png
  SWIPO-iOS/Assets.xcassets/Payment/payment_piece.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Payment/payment_piece.imageset/payment_piece.png
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_coming_soon.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Swipay/swipay_coming_soon.imageset/swipay_coming_soon.png
  SWIPO-iOS/Login/LoginView.swift
  SWIPO-iOS/Main/Swipay/SwipayView.swift
  SWIPO-iOS/Main/Swipstone/SwipstoneView.swift
  SWIPO-iOS/Payment/PaymentFinishView.swift
  SWIPO-iOS/Payment/PaymentShortageModal.swift
  SWIPO-iOS/Payment/PaymentView.swift
  SWIPO-iOS/Payment/QRScannerView.swift
Labels: 👾 Feat

#43 [NETWORK] 애플 소셜로그인 및 회원가입 API 연동 구현
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/App/SWIPO_iOSApp.swift
  SWIPO-iOS/Join/JoinModel.swift
  SWIPO-iOS/Join/JoinView.swift
  SWIPO-iOS/Join/JoinViewModel.swift
  SWIPO-iOS/Login/LoginModel.swift
  SWIPO-iOS/Login/LoginView.swift
  SWIPO-iOS/Login/LoginViewModel.swift
  SWIPO-iOS/Network/Base/APITask.swift
  SWIPO-iOS/Network/Base/BaseResponse.swift
  SWIPO-iOS/Network/Base/NetworkManager.swift
  SWIPO-iOS/Network/Join/JoinEndPoint.swift
  SWIPO-iOS/Network/Join/JoinService.swift
  SWIPO-iOS/Network/Login/LoginEndPoint.swift
  SWIPO-iOS/Network/Login/LoginService.swift
  SWIPO-iOS/Password/PasswordView.swift
Labels: 🌐 Network

#46 [NETWORK] 토큰 재발급 기능 구현
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/Join/JoinViewModel.swift
  SWIPO-iOS/Login/LoginViewModel.swift
  SWIPO-iOS/Network/Auth/AuthEndPoint.swift
  SWIPO-iOS/Network/Auth/AuthService.swift
  SWIPO-iOS/Network/Base/Interceptor.swift
  SWIPO-iOS/Network/Join/JoinService.swift
  SWIPO-iOS/Network/Login/LoginEndPoint.swift
  SWIPO-iOS/Network/Login/LoginService.swift
Labels: 🌐 Network

#47 [FEAT] 내 주변 UI 디자인 수정 반영 - 2
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/Assets.xcassets/Nearby/Category/divider.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/Category/divider.imageset/divider@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Category/divider.imageset/divider@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Category/lab.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/Category/lab.imageset/lab@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Category/lab.imageset/lab@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Category/shadow.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/Category/shadow.imageset/shadow@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Category/shadow.imageset/shadow@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/sample5.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/Store/sample5.imageset/sample5@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Store/sample5.imageset/sample5@3x.png
  SWIPO-iOS/Main/Nearby/Category/CategoryCurationView.swift
  SWIPO-iOS/Main/Nearby/Category/CategoryDefaultView.swift
  SWIPO-iOS/Main/Nearby/Category/CategoryLabView.swift
  SWIPO-iOS/Main/Nearby/Category/CategoryModel.swift
  SWIPO-iOS/Main/Nearby/Category/CategoryRankingView.swift
  SWIPO-iOS/Main/Nearby/Category/CategoryTasteView.swift
  SWIPO-iOS/Main/Nearby/Category/CategoryTitleView.swift
  SWIPO-iOS/Main/Nearby/Category/CategoryView.swift
  SWIPO-iOS/Main/Nearby/Category/CategoryViewModel.swift
  SWIPO-iOS/Main/Nearby/NearbyView.swift
Labels: 👾 Feat

#51 [DESIGN] 페이 충전 이미지 투명도 설정
  SWIPO-iOS/Main/Swipay/PayCharge/PayChargeView.swift
Labels: 🎨 Design

#55 [NETWORK] 스위포인트 카드 등록 API 구현 및 소셜로그인 API 수정
  SWIPO-iOS/Assets.xcassets/Swipoint/swipoint_tutorial1.imageset/swipoint_tutorial1.png
  SWIPO-iOS/Assets.xcassets/Swipoint/swipoint_tutorial2.imageset/swipoint_tutorial2.png
  SWIPO-iOS/Assets.xcassets/Swipoint/swipoint_tutorial3.imageset/swipoint_tutorial3.png
  SWIPO-iOS/Join/JoinViewModel.swift
  SWIPO-iOS/Join/Terms/TermsView.swift
  SWIPO-iOS/Login/LoginView.swift
  SWIPO-iOS/Login/LoginViewModel.swift
  SWIPO-iOS/Main/MainView.swift
  SWIPO-iOS/Main/Swipay/SwipayView.swift
  SWIPO-iOS/Main/Swipoint/Custom/CustomRegisterView.swift
  SWIPO-iOS/Main/Swipoint/Custom/CustomView.swift
  SWIPO-iOS/Main/Swipoint/Custom/CustomViewModel.swift
  SWIPO-iOS/Network/Base/NetworkManager.swift
  SWIPO-iOS/Network/Custom/CustomEndPoint.swift
  SWIPO-iOS/Network/Custom/CustomService.swift
  SWIPO-iOS/Password/PasswordView.swift
Labels: 🌐 Network

#57 [NETWORK] 스윕스톤 스왑 API 연동 구현
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/Common/MainNavigationBar.swift
  SWIPO-iOS/Main/MainView.swift
  SWIPO-iOS/Main/Swipay/SwipayView.swift
  SWIPO-iOS/Main/Swipay/SwipayViewModel.swift
  SWIPO-iOS/Main/Swipstone/SwipstoneAchiveModal.swift
  SWIPO-iOS/Main/Swipstone/SwipstoneModel.swift
  SWIPO-iOS/Main/Swipstone/SwipstoneView.swift
  SWIPO-iOS/Main/Swipstone/SwipstoneViewModel.swift
Labels: 🌐 Network

#63 [NETWORK] Store API 연결
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/Main/Nearby/MapViewModel.swift
  SWIPO-iOS/Main/Nearby/NearbyView.swift
  SWIPO-iOS/Main/Nearby/StoreList/StoreModel.swift
  SWIPO-iOS/Network/Store/StoreEndPoint.swift
  SWIPO-iOS/Network/Store/StoreRequest/StoreMapRequest.swift
  SWIPO-iOS/Network/Store/StoreRequest/StoreReviewRequest.swift
  SWIPO-iOS/Network/Store/StoreRequest/StoreSearchRequest.swift
  SWIPO-iOS/Network/Store/StoreRequest/StoreWishRequest.swift
  SWIPO-iOS/Network/Store/StoreResponse/StoreDetailResponse.swift
  SWIPO-iOS/Network/Store/StoreResponse/StoreMapResponse.swift
  SWIPO-iOS/Network/Store/StoreResponse/StoreSearchResponse.swift
  SWIPO-iOS/Network/Store/StoreResponse/StoreTabResponse.swift
  SWIPO-iOS/Network/Store/StoreService.swift
Labels: 👾 Feat

#64 [NETWORK] 스위포인트 이전 API 연동 구현
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/App/SWIPO_iOSApp.swift
  SWIPO-iOS/Common/Lottie/LottieView.swift
  SWIPO-iOS/Common/Lottie/splash.json
  SWIPO-iOS/Common/Lottie/splashsplash.json
  SWIPO-iOS/Main/Swipay/SwipayModel.swift
  SWIPO-iOS/Main/Swipay/SwipayViewModel.swift
  SWIPO-iOS/Main/Swipoint/Custom/CustomRegisterView.swift
  SWIPO-iOS/Main/Swipoint/Modal/LocationNewModal.swift
  SWIPO-iOS/Main/Swipoint/SwipointExchange/SwipointExchangeCompleteModal.swift
  SWIPO-iOS/Main/Swipoint/SwipointExchange/SwipointExchangeModal.swift
  SWIPO-iOS/Main/Swipoint/SwipointExchange/SwipointExchangeModel.swift
  SWIPO-iOS/Main/Swipoint/SwipointExchange/SwipointExchangeView.swift
  SWIPO-iOS/Main/Swipoint/SwipointExchange/SwipointExchangeViewModel.swift
  SWIPO-iOS/Main/Swipoint/SwipointExchange/SwipstoneSelectListView.swift
  SWIPO-iOS/Main/Swipoint/SwipointExchange/SwipstoneSelectModal.swift
  SWIPO-iOS/Main/Swipoint/SwipointView.swift
  SWIPO-iOS/Network/SwipExchange/SwipExchangeEndPoint.swift
  SWIPO-iOS/Network/SwipExchange/SwipExchangeService.swift
Labels: 🌐 Network

#66 [NETWORK] 내 주변 맵 API 연결
  SWIPO-iOS.xcodeproj/project.pbxproj
  SWIPO-iOS/Assets.xcassets/Nearby/Category/lab_location.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/Category/lab_location.imageset/lab_location@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/Category/lab_location.imageset/lab_location@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/tooltip.imageset/tooltip@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/tooltip.imageset/tooltip@3x.png
  SWIPO-iOS/Assets.xcassets/Nearby/tooltip2.imageset/Contents.json
  SWIPO-iOS/Assets.xcassets/Nearby/tooltip2.imageset/tooltip@2x.png
  SWIPO-iOS/Assets.xcassets/Nearby/tooltip2.imageset/tooltip@3x.png
  SWIPO-iOS/Main/Nearby/Category/CategoryLabView.swift
  SWIPO-iOS/Main/Nearby/MapModel.swift
  SWIPO-iOS/Main/Nearby/MapView.swift
  SWIPO-iOS/Main/Nearby/MapViewController.swift
  SWIPO-iOS/Main/Nearby/MapViewModel.swift
  SWIPO-iOS/Main/Nearby/NearbyView.swift
  SWIPO-iOS/Main/Swipay/SwipayViewModel.swift
  SWIPO-iOS/Network/Base/BaseResponse.swift
  SWIPO-iOS/Network/Store/StoreResponse/StoreMapResponse.swift
  SWIPO-iOS/Network/Store/StoreResponse/StoreTabResponse.swift
  SWIPO-iOS/Network/Store/StoreService.swift
Labels: 🌐 Network
